### ISSUE TITLE
[typescript] Please export the type of a `Resolvable`

### ISSUE THREAD

**Issue by domq** [WhiteAutumn/resolvable-promise#5]
Hello WhiteAutumn, kudos for this great module. Today I found myself having to type an object with a `Resolvable` field in it. I did

```typescript
import { Resolvable as ResolvableType } from 'resolvable-promise/dist/types';    // CHEATING!

type MyType = {
      isItdoneAlready: ResolvableType<void>;
};
```

I am admittedly not a black belt in TypeScript yet, so perhaps there already exists a way to achieve this without cheating?

If so, kindly add it to the documentation. If not, please re-export that type somehow.

Thanks in advance!

**Comment by WhiteAutumn** [comment]
> perhaps there already exists a way to achieve this without cheating?

No, unfortunately not as it stands. I agree this is cumbersome, but unfortunately it is not as simple as adding the type export. In my effort to make the package compatible with both esm and commonjs this was the compromise I decided to make.

However, that was then! Think I have an idea on how to get the type exported properly and have been thinking of rewriting this package for a while. This might just give me the kick in the ass to sit down and do it 😄

I'll @ you here when the version gets published, if I do get it working.

**Comment by WhiteAutumn** [comment]
Version 3.0.0 has been released @domq 

With this version it's possible to use the imported Resolvable as a type on its own!
Here's an example:
```js
import Resolvable from "resolvable-promise";

let resolvable: Resolvable<number>;
resolvable = new Resolvable();

resolvable.then(num => console.log(`${num} + ${num} = ${num + num}`));
resolvable.resolve(10);
```
```
10 + 10 = 20
```

**Comment by domq** [comment]
Apologies for not giving any news earlier, I was busy with a variety of Chinese fire drills last week, but I just got around to testing your new release. It works flawlessly! Thank you so much!
